USE [master]
GO
CREATE LOGIN Paul WITH PASSWORD=N'P@ssw0rd', 
	DEFAULT_DATABASE=[Stock], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
USE VenteBD
GO
CREATE USER Paul FOR LOGIN Paul;
go
CREATE SCHEMA RH
GO
ALTER USER [Paul] WITH DEFAULT_SCHEMA=[RH]
GO
CREATE TABLE RH.t2 (id int)
--
GRANT DELETE ON SCHEMA::[RH] TO [Paul]
GO
GRANT SELECT ON SCHEMA::[RH] TO [Paul]
GO
DENY DELETE ON [RH].[t2] TO [Paul]
GO
CREATE PROC f1
as
delete Produit
GO
GRANT EXECUTE ON SCHEMA::[RH] TO [Paul]
GO
