-- Créer un base de données Ventes contenant les tables suivantes :
-- Table Produit : id, Libelle, Prix
-- Table Commande : id, NoCommande, DateCommande
-- Table LigneCommande : id, , Commande, Produit, Quantite, PrixUnitaire